/**
 * MECE分類による包括的な補助金データ追加スクリプト
 *
 * カテゴリ:
 * 1. 経済産業省系（創業・設備投資・DX）
 * 2. 厚生労働省系（雇用・人材育成・働き方改革）
 * 3. 農林水産省系（農業・林業・水産業）
 * 4. 環境省系（脱炭素・省エネ・再エネ）
 * 5. 国土交通省系（建設・観光・物流）
 * 6. 総務省・文科省系（地域活性化・研究開発）
 * 7. 都道府県別（主要都市）
 *
 * 実行方法: npx tsx scripts/add-comprehensive-subsidies.ts
 */

import { config } from 'dotenv';
config({ path: '.env.local' });
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY);

type SubsidyInput = {
  id: string;
  title: string;
  description: string;
  max_amount: number;
  subsidy_rate?: string;
  target_area: string[];
  industry: string[];
  use_purpose: string;
  target_employees?: string;
  start_date: string;
  end_date: string;
};

// ========================================
// 1. 経済産業省系（創業・設備投資・DX・海外展開）
// ========================================
const METI_SUBSIDIES: SubsidyInput[] = [
  {
    id: 'meti-001',
    title: '事業再構築補助金（第13回・成長分野進出枠）',
    description: '新市場進出、事業・業種転換、業態転換等により事業再構築を図る中小企業等を支援。成長分野（グリーン、DX等）への進出を重点支援。',
    max_amount: 70000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-07-31',
  },
  {
    id: 'meti-002',
    title: '事業再構築補助金（第13回・コロナ回復加速化枠）',
    description: 'コロナ禍の影響を受けた事業者の売上回復・成長を加速化するための事業再構築を支援。',
    max_amount: 30000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業', '生活関連サービス業、娯楽業', '卸売業、小売業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-07-31',
  },
  {
    id: 'meti-003',
    title: 'Go-Tech事業（成長型中小企業等研究開発支援事業）',
    description: '中小企業者等が大学・公設試等と連携して行う、ものづくり基盤技術及びサービスの高度化に向けた研究開発等を支援。',
    max_amount: 100000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '学術研究、専門・技術サービス業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-02-01',
    end_date: '2025-04-30',
  },
  {
    id: 'meti-004',
    title: 'SBIR推進プログラム（中小企業技術革新制度）',
    description: '研究開発型スタートアップ・中小企業による革新的技術の事業化を、研究開発から事業化まで一貫して支援。',
    max_amount: 500000000,
    subsidy_rate: '2/3〜定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '学術研究、専門・技術サービス業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'meti-005',
    title: 'JAPANブランド育成支援等事業',
    description: '複数の中小企業等が連携して、海外展開やインバウンド需要の獲得を目的に行う、新商品・サービスの開発等を支援。',
    max_amount: 20000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-03-01',
    end_date: '2025-05-31',
  },
  {
    id: 'meti-006',
    title: '中小企業海外ビジネス人材育成支援事業',
    description: '中小企業の海外展開に必要な人材育成を支援。海外ビジネスの実務研修、語学研修等の費用を補助。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '人材育成を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'meti-007',
    title: '伝統的工芸品産業支援補助金',
    description: '伝統的工芸品産業の振興のため、後継者育成、需要開拓、意匠開発等の取組を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['製造業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'meti-008',
    title: '中小企業組合等課題対応支援事業',
    description: '中小企業組合等が行う、人材確保、生産性向上、新事業展開等の課題解決に向けた取組を支援。',
    max_amount: 10000000,
    subsidy_rate: '6/10',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '建設業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'meti-009',
    title: '商店街活性化・観光消費創出事業',
    description: '商店街等が実施する、消費喚起イベント、プロモーション活動、観光商品開発等の取組を支援。',
    max_amount: 20000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-05-01',
    end_date: '2025-07-31',
  },
  {
    id: 'meti-010',
    title: '地域商業機能複合化推進事業',
    description: '商店街等における商業機能と地域福祉・子育て支援等の複合化を図る取組を支援。',
    max_amount: 50000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '医療、福祉', '教育、学習支援業'],
    use_purpose: 'まちづくり・地域振興支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'meti-011',
    title: '中小企業等事業再構築促進基金（グリーン成長枠）',
    description: 'グリーン分野での事業再構築を通じて高い成長を目指す事業者を支援。研究開発・技術開発含む。',
    max_amount: 150000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['製造業', '電気・ガス・熱供給・水道業', '建設業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-07-31',
  },
  {
    id: 'meti-012',
    title: '地域DX促進活動支援事業',
    description: '地域の中小企業のDXを促進するため、地域の支援機関が行うDX推進活動を支援。',
    max_amount: 30000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['情報通信業', '卸売業、小売業', '製造業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'meti-013',
    title: '成長型中小企業等研究開発支援事業（一般型）',
    description: '中小企業が大学・研究機関等と連携して行う研究開発及びその成果の事業化を支援。',
    max_amount: 45000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '学術研究、専門・技術サービス業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-02-01',
    end_date: '2025-04-30',
  },
  {
    id: 'meti-014',
    title: '中小企業等海外出願・侵害対策支援事業',
    description: '中小企業等の戦略的な海外展開を知財面から支援。海外への特許出願、意匠・商標出願、冒認対策等を補助。',
    max_amount: 3000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-01-31',
  },
  {
    id: 'meti-015',
    title: '中小企業活性化・事業承継総合支援事業',
    description: '中小企業の経営改善・事業再生・事業承継を一体的に支援。専門家派遣、計画策定支援等。',
    max_amount: 2000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '事業を引き継ぎたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
];

// ========================================
// 2. 厚生労働省系（雇用・人材育成・働き方改革）
// ========================================
const MHLW_SUBSIDIES: SubsidyInput[] = [
  {
    id: 'mhlw-001',
    title: '人材開発支援助成金（人材育成支援コース）',
    description: '事業主が雇用する労働者に対して、職務に関連した専門的な知識及び技能を習得させるための職業訓練等を実施した場合に助成。',
    max_amount: 10000000,
    subsidy_rate: '45%〜75%',
    target_area: ['全国'],
    industry: ['製造業', '建設業', '情報通信業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '人材育成を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-002',
    title: '人材開発支援助成金（教育訓練休暇等付与コース）',
    description: '有給教育訓練休暇制度を導入し、労働者が当該休暇を取得して訓練を受けた場合に助成。',
    max_amount: 360000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '人材育成を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-003',
    title: '人材開発支援助成金（事業展開等リスキリング支援コース）',
    description: '新規事業の立ち上げ等に伴い、新たな分野で必要となる知識・技能を習得させるための訓練を実施した場合に助成。',
    max_amount: 10000000,
    subsidy_rate: '75%',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '人材育成を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-004',
    title: '両立支援等助成金（出生時両立支援コース）',
    description: '男性労働者が育児休業を取得しやすい雇用環境整備や業務体制整備を行い、育児休業を取得した場合に助成。',
    max_amount: 570000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', '医療、福祉', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-005',
    title: '両立支援等助成金（育児休業等支援コース）',
    description: '育児休業の円滑な取得・職場復帰のための取組を行った事業主に対して助成。',
    max_amount: 360000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', '医療、福祉', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-006',
    title: '両立支援等助成金（介護離職防止支援コース）',
    description: '仕事と介護の両立支援に関する取組を行った事業主に対して助成。介護休業取得、介護両立支援制度導入等。',
    max_amount: 570000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', '医療、福祉', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-007',
    title: '働き方改革推進支援助成金（労働時間短縮・年休促進支援コース）',
    description: '生産性向上に資する設備・機器の導入等により、時間外労働の削減、年次有給休暇の取得促進に取り組む中小企業を支援。',
    max_amount: 2500000,
    subsidy_rate: '3/4',
    target_area: ['全国'],
    industry: ['製造業', '建設業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-11-30',
  },
  {
    id: 'mhlw-008',
    title: '働き方改革推進支援助成金（勤務間インターバル導入コース）',
    description: '勤務間インターバル制度の導入に取り組む中小企業事業主を支援。',
    max_amount: 1200000,
    subsidy_rate: '3/4',
    target_area: ['全国'],
    industry: ['製造業', '運輸業、郵便業', '情報通信業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-11-30',
  },
  {
    id: 'mhlw-009',
    title: '働き方改革推進支援助成金（団体推進コース）',
    description: '中小企業事業主の団体等が、傘下企業の労働条件の改善のために取り組む活動を支援。',
    max_amount: 5000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '建設業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-09-30',
  },
  {
    id: 'mhlw-010',
    title: '特定求職者雇用開発助成金（特定就職困難者コース）',
    description: '高年齢者、障害者、母子家庭の母等の就職困難者を雇い入れた事業主に対して助成。',
    max_amount: 2400000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '医療、福祉', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-011',
    title: '特定求職者雇用開発助成金（成長分野等人材確保・育成コース）',
    description: '成長分野（デジタル・グリーン等）の業務に従事させる労働者を雇い入れた事業主に対して助成。',
    max_amount: 1800000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['情報通信業', '製造業', '電気・ガス・熱供給・水道業'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-012',
    title: 'トライアル雇用助成金（一般トライアルコース）',
    description: '職業経験の不足等から就職が困難な求職者を試行雇用した事業主に対して助成。',
    max_amount: 120000,
    subsidy_rate: '定額（月額4万円×3ヶ月）',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-013',
    title: '65歳超雇用推進助成金（65歳超継続雇用促進コース）',
    description: '65歳以上への定年引上げ、定年廃止、66歳以上の継続雇用制度の導入を行う事業主を支援。',
    max_amount: 1600000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '建設業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-014',
    title: '65歳超雇用推進助成金（高年齢者無期雇用転換コース）',
    description: '50歳以上かつ定年年齢未満の有期契約労働者を無期雇用に転換した事業主を支援。',
    max_amount: 480000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '建設業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-015',
    title: '障害者雇用安定助成金（障害者職場定着支援コース）',
    description: '障害者の職場定着を図るために、職場支援員の配置、職場復帰支援等を行う事業主を支援。',
    max_amount: 1200000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '医療、福祉', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-016',
    title: '雇用調整助成金',
    description: '景気変動等により事業活動の縮小を余儀なくされた事業主が、休業等により労働者の雇用維持を図る場合に助成。',
    max_amount: 8490,
    subsidy_rate: '2/3〜3/4（日額上限）',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-017',
    title: '産業雇用安定助成金（産業連携人材確保等支援コース）',
    description: '景気変動等の影響を受けた事業主が、在籍型出向により労働者の雇用維持を図る場合に助成。',
    max_amount: 2500000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mhlw-018',
    title: '中途採用等支援助成金（中途採用拡大コース）',
    description: '中途採用者の雇用管理制度を整備し、中途採用の拡大を図った事業主を支援。',
    max_amount: 500000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['製造業', '情報通信業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '雇用・職場環境を改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
];

// ========================================
// 3. 農林水産省系（農業・林業・水産業・食品）
// ========================================
const MAFF_SUBSIDIES: SubsidyInput[] = [
  {
    id: 'maff-001',
    title: '農業次世代人材投資資金（経営開始型）',
    description: '新規就農者に対して、農業経営を開始してから経営が安定するまでの間、年間最大150万円を最長5年間交付。',
    max_amount: 7500000,
    subsidy_rate: '定額（年150万円×5年）',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'maff-002',
    title: '経営発展支援事業',
    description: '新規就農者が経営発展のために必要な機械・施設等の導入を支援。国が1/2、都道府県が1/4を補助。',
    max_amount: 10000000,
    subsidy_rate: '3/4',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'maff-003',
    title: '農地利用効率化等支援交付金',
    description: '農地の集積・集約化、新規就農者の確保・育成、経営発展に向けた機械・施設の導入等を支援。',
    max_amount: 30000000,
    subsidy_rate: '1/2〜定額',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'maff-004',
    title: '産地生産基盤パワーアップ事業',
    description: '収益力強化に計画的に取り組む産地に対し、必要な農業機械のリース導入、集出荷施設等の整備を支援。',
    max_amount: 100000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'maff-005',
    title: '畜産クラスター事業',
    description: '畜産クラスター計画に位置づけられた中心的な経営体が行う施設整備、機械導入等を支援。',
    max_amount: 200000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'maff-006',
    title: '持続的生産強化対策事業（産地ツアー）',
    description: '野菜・果樹・花きの産地において、労働力不足に対応した省力化技術の導入、産地の若返り等を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'maff-007',
    title: 'スマート農業技術の開発・実証プロジェクト',
    description: 'ロボット、AI、IoT等の先端技術を活用したスマート農業の開発・実証を支援。',
    max_amount: 150000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['農業、林業', '情報通信業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'maff-008',
    title: '農林水産物・食品輸出促進緊急対策事業',
    description: '農林水産物・食品の輸出拡大に向けた施設整備、販路開拓、輸出先国の規制対応等を支援。',
    max_amount: 50000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['農業、林業', '漁業', '製造業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'maff-009',
    title: '食品産業の輸出向けHACCP等対応施設整備事業',
    description: '輸出先国のHACCP等の基準に対応した施設・設備の整備を支援。',
    max_amount: 150000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'maff-010',
    title: '6次産業化支援事業',
    description: '農林漁業者が自ら生産した農林水産物を活用して新商品開発・販路開拓等を行う取組を支援。',
    max_amount: 30000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['農業、林業', '漁業', '製造業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'maff-011',
    title: '林業施設整備等利子助成事業',
    description: '林業経営の安定に必要な施設整備等に係る借入金の利子を助成。',
    max_amount: 5000000,
    subsidy_rate: '利子助成',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: '資金繰りを改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'maff-012',
    title: '漁業経営セーフティーネット構築事業',
    description: '燃油・配合飼料の価格上昇による漁業経営への影響を緩和するため、積立方式による補填を実施。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['漁業'],
    use_purpose: '資金繰りを改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'maff-013',
    title: '国産農林水産物等販路多様化緊急対策事業',
    description: 'インバウンド需要等の減少により影響を受けた国産農林水産物等の販路多様化の取組を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2〜定額',
    target_area: ['全国'],
    industry: ['農業、林業', '漁業', '卸売業、小売業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'maff-014',
    title: '有機農業推進総合対策事業',
    description: '有機農業の生産から消費まで一貫した取組を支援。技術習得、販路開拓、理解醸成等。',
    max_amount: 20000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['農業、林業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'maff-015',
    title: 'みどりの食料システム戦略推進交付金',
    description: '環境負荷低減と持続的発展に向けた地域ぐるみのモデル地区の創出を支援。',
    max_amount: 50000000,
    subsidy_rate: '1/2〜定額',
    target_area: ['全国'],
    industry: ['農業、林業', '漁業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
];

// ========================================
// 4. 環境省系（脱炭素・省エネ・再エネ・廃棄物）
// ========================================
const MOE_SUBSIDIES: SubsidyInput[] = [
  {
    id: 'moe-001',
    title: '工場・事業場における先導的な脱炭素化取組推進事業（SHIFT事業）',
    description: '工場・事業場でのCO2削減目標達成に向けた設備更新、電化・燃料転換等の脱炭素化を支援。',
    max_amount: 100000000,
    subsidy_rate: '1/3〜1/2',
    target_area: ['全国'],
    industry: ['製造業', '電気・ガス・熱供給・水道業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-002',
    title: '建築物等の脱炭素化・レジリエンス強化促進事業',
    description: '既存建築物のZEB化改修、省エネ設備導入、再エネ設備導入等を支援。',
    max_amount: 50000000,
    subsidy_rate: '1/3〜2/3',
    target_area: ['全国'],
    industry: ['建設業', '不動産業、物品賃貸業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-003',
    title: '地域脱炭素移行・再エネ推進交付金',
    description: '地方自治体と連携した地域の脱炭素化に向けた再エネ設備導入、省エネ改修等を支援。',
    max_amount: 200000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['電気・ガス・熱供給・水道業', '建設業', '製造業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-004',
    title: '脱炭素社会実現のための都市間連携事業',
    description: '都市間連携を通じたJCMプロジェクト形成、都市の脱炭素化を支援。',
    max_amount: 30000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['建設業', '電気・ガス・熱供給・水道業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-005',
    title: '脱炭素型循環経済システム構築促進事業',
    description: 'プラスチック等の資源循環高度化設備導入、リサイクル技術開発等を支援。',
    max_amount: 50000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-006',
    title: '廃棄物処理施設を核とした地域循環共生圏構築促進事業',
    description: '廃棄物処理施設を核とした地域のエネルギーセンター整備、廃熱利用等を支援。',
    max_amount: 300000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['サービス業(他に分類されないもの)', '電気・ガス・熱供給・水道業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-007',
    title: '二酸化炭素排出抑制対策事業費等補助金（省エネ設備導入）',
    description: '中小企業等が行う省エネルギー設備の導入を支援。空調、照明、変圧器等。',
    max_amount: 10000000,
    subsidy_rate: '1/3',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'moe-008',
    title: 'PPA活用等による地域の再エネ主力化・レジリエンス強化促進事業',
    description: 'PPAモデル等を活用した太陽光発電、蓄電池等の導入を支援。',
    max_amount: 20000000,
    subsidy_rate: '1/2〜2/3',
    target_area: ['全国'],
    industry: ['電気・ガス・熱供給・水道業', '建設業', '製造業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  {
    id: 'moe-009',
    title: '電動車の普及促進に向けた充電インフラ等導入促進補助金',
    description: '電気自動車等の充電インフラ設備、V2H設備等の導入を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '運輸業、郵便業', 'サービス業(他に分類されないもの)'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'moe-010',
    title: 'コールドチェーンを支える冷凍冷蔵機器の脱フロン・脱炭素化推進事業',
    description: '省エネ型自然冷媒機器への転換を支援。冷凍冷蔵倉庫、食品小売店等。',
    max_amount: 30000000,
    subsidy_rate: '1/3',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '運輸業、郵便業', '倉庫業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'moe-011',
    title: 'ESGリース促進事業',
    description: '脱炭素機器をリースで導入する場合に、リース料の一部を助成。',
    max_amount: 5000000,
    subsidy_rate: 'リース料の2%〜4%',
    target_area: ['全国'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'moe-012',
    title: 'グリーンボンド等促進体制整備支援事業',
    description: 'グリーンボンドの発行に伴う外部レビュー費用、コンサルティング費用等を支援。',
    max_amount: 25000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['金融業、保険業', '製造業', '電気・ガス・熱供給・水道業'],
    use_purpose: '資金繰りを改善したい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
];

// ========================================
// 5. 国土交通省系（建設・観光・物流・住宅）
// ========================================
const MLIT_SUBSIDIES: SubsidyInput[] = [
  {
    id: 'mlit-001',
    title: '地域観光資源の多言語解説整備支援事業',
    description: '観光地における多言語解説文の作成、解説板・音声ガイド等の整備を支援。',
    max_amount: 15000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-002',
    title: '観光地域づくり法人（DMO）形成・確立支援事業',
    description: '観光地域づくり法人（DMO）の形成・確立に向けた取組を支援。',
    max_amount: 20000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: 'まちづくり・地域振興支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-003',
    title: '訪日外国人旅行者周遊促進事業',
    description: '訪日外国人旅行者の地方誘客・周遊促進のためのコンテンツ造成等を支援。',
    max_amount: 30000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業', '運輸業、郵便業', '生活関連サービス業、娯楽業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-004',
    title: 'サステナブルな観光コンテンツ強化モデル事業',
    description: '持続可能な観光地域づくりに向けた先進的な観光コンテンツの開発を支援。',
    max_amount: 20000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-005',
    title: 'トラック輸送の省エネ化推進事業',
    description: '燃費性能の高いトラックへの代替促進、エコドライブの推進等を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/3',
    target_area: ['全国'],
    industry: ['運輸業、郵便業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-006',
    title: '物流総合効率化法に基づく支援措置',
    description: '物流の総合化・効率化に資する施設整備、設備導入等を支援。認定計画に対する税制特例等。',
    max_amount: 100000000,
    subsidy_rate: '税制特例等',
    target_area: ['全国'],
    industry: ['運輸業、郵便業', '卸売業、小売業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'mlit-007',
    title: '長期優良住宅化リフォーム推進事業',
    description: '既存住宅の長寿命化・省エネ化等のリフォームを支援。',
    max_amount: 2500000,
    subsidy_rate: '1/3',
    target_area: ['全国'],
    industry: ['建設業', '不動産業、物品賃貸業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'mlit-008',
    title: '空き家対策総合支援事業',
    description: '空き家の活用・除却等に関する取組を支援。',
    max_amount: 30000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['建設業', '不動産業、物品賃貸業'],
    use_purpose: 'まちづくり・地域振興支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'mlit-009',
    title: '住宅・建築物安全ストック形成事業',
    description: '住宅・建築物の耐震化を支援。耐震診断、耐震改修等。',
    max_amount: 10000000,
    subsidy_rate: '1/3〜1/2',
    target_area: ['全国'],
    industry: ['建設業', '不動産業、物品賃貸業'],
    use_purpose: '安全・防災対策支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'mlit-010',
    title: '建設業の人材確保・育成に向けた取組支援',
    description: '建設業の担い手確保に向けた研修実施、広報活動等を支援。',
    max_amount: 5000000,
    subsidy_rate: '定額',
    target_area: ['全国'],
    industry: ['建設業'],
    use_purpose: '人材育成を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'mlit-011',
    title: 'ICTを活用した工事の生産性向上事業',
    description: 'ICT建機の導入、3次元データ活用等による建設現場の生産性向上を支援。',
    max_amount: 20000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['建設業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'mlit-012',
    title: '地域交通グリーン化事業',
    description: '電気バス、電気タクシー、燃料電池バス等の導入を支援。',
    max_amount: 25000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['運輸業、郵便業'],
    use_purpose: 'エコ・SDGs活動支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
];

// ========================================
// 6. 都道府県別補助金（主要都市）
// ========================================
const PREFECTURE_SUBSIDIES: SubsidyInput[] = [
  // 北海道
  {
    id: 'pref-hokkaido-001',
    title: '北海道中小企業新応援ファンド事業',
    description: '北海道内の中小企業が行う新商品開発、販路開拓等を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['北海道'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'pref-hokkaido-002',
    title: '北海道食品産業振興事業',
    description: '道産食品の高付加価値化、販路拡大等を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['北海道'],
    industry: ['製造業', '卸売業、小売業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 宮城県
  {
    id: 'pref-miyagi-001',
    title: '宮城県中小企業等再起支援事業',
    description: '新型コロナの影響を受けた県内中小企業の事業継続・再起を支援。',
    max_amount: 3000000,
    subsidy_rate: '3/4',
    target_area: ['宮城県'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 埼玉県
  {
    id: 'pref-saitama-001',
    title: '埼玉県先端産業創造プロジェクト',
    description: '県内中小企業の先端産業分野への参入を支援。医療機器、航空宇宙等。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['埼玉県'],
    industry: ['製造業', '情報通信業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 千葉県
  {
    id: 'pref-chiba-001',
    title: 'ちば中小企業元気づくり基金事業',
    description: '千葉県内中小企業の新事業展開、経営革新を支援。',
    max_amount: 2000000,
    subsidy_rate: '1/2',
    target_area: ['千葉県'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 東京都（追加分）
  {
    id: 'pref-tokyo-002',
    title: '東京都地域中小企業応援ファンド事業',
    description: '東京の「地域資源」を活用した新事業開発を支援。',
    max_amount: 8000000,
    subsidy_rate: '1/2',
    target_area: ['東京都'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-01-31',
  },
  {
    id: 'pref-tokyo-003',
    title: '東京都中小企業知的財産活用支援事業',
    description: '特許権・商標権等の取得、知財戦略策定を支援。',
    max_amount: 1000000,
    subsidy_rate: '1/2',
    target_area: ['東京都'],
    industry: ['製造業', '情報通信業', '卸売業、小売業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-01-31',
  },
  {
    id: 'pref-tokyo-004',
    title: '東京都事業承継・再生支援事業',
    description: '中小企業の円滑な事業承継、事業再生を支援。',
    max_amount: 2000000,
    subsidy_rate: '2/3',
    target_area: ['東京都'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '事業を引き継ぎたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-01-31',
  },
  // 神奈川県
  {
    id: 'pref-kanagawa-001',
    title: 'かながわ成長産業イノベーション支援事業',
    description: 'ロボット、新エネルギー、健康医療等の成長分野への参入を支援。',
    max_amount: 20000000,
    subsidy_rate: '1/2',
    target_area: ['神奈川県'],
    industry: ['製造業', '情報通信業', '医療、福祉'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'pref-kanagawa-002',
    title: '神奈川県中小企業販路開拓支援事業',
    description: '県内中小企業の販路開拓、マーケティング強化を支援。',
    max_amount: 3000000,
    subsidy_rate: '1/2',
    target_area: ['神奈川県'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 愛知県
  {
    id: 'pref-aichi-001',
    title: '愛知県新あいち創造産業立地補助金',
    description: '県内での設備投資、研究開発拠点設置等を支援。',
    max_amount: 100000000,
    subsidy_rate: '5〜10%',
    target_area: ['愛知県'],
    industry: ['製造業', '情報通信業', '学術研究、専門・技術サービス業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-02-28',
  },
  {
    id: 'pref-aichi-002',
    title: '愛知県中小企業応援ファンド事業',
    description: '県内中小企業の新事業展開、技術開発等を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['愛知県'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 大阪府
  {
    id: 'pref-osaka-001',
    title: '大阪府中小企業新製品開発支援事業',
    description: '府内中小企業の新製品・新技術開発を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['大阪府'],
    industry: ['製造業', '情報通信業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'pref-osaka-002',
    title: '大阪産業局スタートアップ支援事業',
    description: 'スタートアップの事業化、成長を支援。',
    max_amount: 5000000,
    subsidy_rate: '2/3',
    target_area: ['大阪府'],
    industry: ['情報通信業', '製造業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '50名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 兵庫県
  {
    id: 'pref-hyogo-001',
    title: 'ひょうご産業活性化センター経営革新支援事業',
    description: '経営革新計画に基づく新事業展開を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['兵庫県'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 広島県
  {
    id: 'pref-hiroshima-001',
    title: '広島県ものづくり企業技術革新支援事業',
    description: '県内製造業の技術開発、生産性向上を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['広島県'],
    industry: ['製造業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 福岡県
  {
    id: 'pref-fukuoka-001',
    title: '福岡県中小企業生産性向上支援事業',
    description: '県内中小企業のDX推進、生産性向上を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['福岡県'],
    industry: ['製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'pref-fukuoka-002',
    title: '福岡県スタートアップ支援事業',
    description: 'スタートアップの創業、成長を支援。',
    max_amount: 10000000,
    subsidy_rate: '2/3',
    target_area: ['福岡県'],
    industry: ['情報通信業', '製造業', 'サービス業(他に分類されないもの)'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '50名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 沖縄県
  {
    id: 'pref-okinawa-001',
    title: '沖縄県産業振興公社中小企業支援事業',
    description: '県内中小企業の経営革新、販路開拓等を支援。',
    max_amount: 3000000,
    subsidy_rate: '2/3',
    target_area: ['沖縄県'],
    industry: ['製造業', '卸売業、小売業', '宿泊業、飲食サービス業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'pref-okinawa-002',
    title: '沖縄県観光産業振興事業',
    description: '沖縄観光の高付加価値化、受入環境整備を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['沖縄県'],
    industry: ['宿泊業、飲食サービス業', '運輸業、郵便業', '生活関連サービス業、娯楽業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
];

// ========================================
// 7. 業種別専門補助金
// ========================================
const INDUSTRY_SUBSIDIES: SubsidyInput[] = [
  // IT・情報通信
  {
    id: 'ind-it-001',
    title: 'IT導入補助金2025（セキュリティ対策推進枠）',
    description: 'サイバーセキュリティ対策のためのITツール導入を支援。',
    max_amount: 1000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['情報通信業', '製造業', '卸売業、小売業', 'サービス業(他に分類されないもの)'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'ind-it-002',
    title: 'クラウド利用促進機構認定制度活用事業',
    description: 'クラウドサービスの導入・活用を支援。',
    max_amount: 3000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['情報通信業', '製造業', '卸売業、小売業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 製造業
  {
    id: 'ind-mfg-001',
    title: '中小企業等経営強化法に基づく支援措置',
    description: '経営力向上計画に基づく設備投資に対する税制優遇等。',
    max_amount: 50000000,
    subsidy_rate: '税制優遇',
    target_area: ['全国'],
    industry: ['製造業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'ind-mfg-002',
    title: '中小企業技術高度化支援事業（サポイン）',
    description: '中小企業者等が行う特定ものづくり基盤技術の高度化を支援。',
    max_amount: 45000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['製造業'],
    use_purpose: '研究開発・実証事業を行いたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-06-30',
  },
  // 飲食・小売
  {
    id: 'ind-retail-001',
    title: '商業・サービス業改善支援事業',
    description: '商業・サービス業の設備投資、業務効率化を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '100名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'ind-retail-002',
    title: 'インバウンド対応力強化支援補助金',
    description: '多言語対応、キャッシュレス決済導入等のインバウンド対応を支援。',
    max_amount: 3000000,
    subsidy_rate: '2/3',
    target_area: ['全国'],
    industry: ['卸売業、小売業', '宿泊業、飲食サービス業', '生活関連サービス業、娯楽業'],
    use_purpose: '販路拡大・海外展開をしたい',
    target_employees: '300名以下',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 医療・福祉
  {
    id: 'ind-med-001',
    title: '医療施設等設備整備補助金',
    description: '医療機関の医療機器、設備の整備を支援。',
    max_amount: 50000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['医療、福祉'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'ind-med-002',
    title: '介護ロボット導入支援事業',
    description: '介護施設における介護ロボットの導入を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['医療、福祉'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'ind-med-003',
    title: 'ICT導入支援事業（介護）',
    description: '介護事業所におけるICT機器の導入を支援。',
    max_amount: 2600000,
    subsidy_rate: '1/2〜3/4',
    target_area: ['全国'],
    industry: ['医療、福祉'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 運輸・物流
  {
    id: 'ind-trans-001',
    title: '運輸事業振興助成交付金',
    description: 'トラック事業者の安全対策、環境対策を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['運輸業、郵便業'],
    use_purpose: '安全・防災対策支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2026-03-31',
  },
  {
    id: 'ind-trans-002',
    title: '自動車運送事業安全総合対策事業',
    description: '運行管理の高度化、先進安全機器の導入を支援。',
    max_amount: 800000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['運輸業、郵便業'],
    use_purpose: '安全・防災対策支援がほしい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 宿泊業
  {
    id: 'ind-hotel-001',
    title: '宿泊施設バリアフリー化促進事業',
    description: '宿泊施設のバリアフリー改修を支援。',
    max_amount: 5000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業'],
    use_purpose: '設備整備・IT導入をしたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  {
    id: 'ind-hotel-002',
    title: '旅館等経営革新支援事業',
    description: '旅館・ホテルの経営革新、生産性向上を支援。',
    max_amount: 10000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['宿泊業、飲食サービス業'],
    use_purpose: '新たな事業を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
  // 教育・学習支援
  {
    id: 'ind-edu-001',
    title: 'リカレント教育推進事業',
    description: '社会人向け教育プログラムの開発・提供を支援。',
    max_amount: 20000000,
    subsidy_rate: '1/2',
    target_area: ['全国'],
    industry: ['教育、学習支援業'],
    use_purpose: '人材育成を行いたい',
    target_employees: '従業員数の制約なし',
    start_date: '2025-04-01',
    end_date: '2025-12-31',
  },
];

// ========================================
// メイン処理
// ========================================
async function main() {
  console.log('='.repeat(60));
  console.log('MECE分類による包括的補助金データ追加');
  console.log('実行日時:', new Date().toLocaleString('ja-JP'));
  console.log('='.repeat(60));

  const allSubsidies = [
    ...METI_SUBSIDIES,
    ...MHLW_SUBSIDIES,
    ...MAFF_SUBSIDIES,
    ...MOE_SUBSIDIES,
    ...MLIT_SUBSIDIES,
    ...PREFECTURE_SUBSIDIES,
    ...INDUSTRY_SUBSIDIES,
  ];

  console.log(`\n追加予定: ${allSubsidies.length}件`);
  console.log(`  - 経済産業省系: ${METI_SUBSIDIES.length}件`);
  console.log(`  - 厚生労働省系: ${MHLW_SUBSIDIES.length}件`);
  console.log(`  - 農林水産省系: ${MAFF_SUBSIDIES.length}件`);
  console.log(`  - 環境省系: ${MOE_SUBSIDIES.length}件`);
  console.log(`  - 国土交通省系: ${MLIT_SUBSIDIES.length}件`);
  console.log(`  - 都道府県別: ${PREFECTURE_SUBSIDIES.length}件`);
  console.log(`  - 業種別専門: ${INDUSTRY_SUBSIDIES.length}件`);

  let successCount = 0;
  let errorCount = 0;

  for (const subsidy of allSubsidies) {
    const record = {
      jgrants_id: subsidy.id,
      name: subsidy.id,
      title: subsidy.title,
      description: subsidy.description,
      max_amount: subsidy.max_amount,
      subsidy_rate: subsidy.subsidy_rate || null,
      target_area: subsidy.target_area,
      industry: subsidy.industry,
      use_purpose: subsidy.use_purpose,
      target_number_of_employees: subsidy.target_employees || null,
      start_date: subsidy.start_date,
      end_date: subsidy.end_date,
      is_active: true,
      updated_at: new Date().toISOString(),
    };

    const { error } = await supabase
      .from('subsidies')
      .upsert(record, { onConflict: 'jgrants_id' });

    if (error) {
      console.error(`エラー: ${subsidy.title} - ${error.message}`);
      errorCount++;
    } else {
      successCount++;
    }
  }

  console.log('\n' + '='.repeat(60));
  console.log('追加完了');
  console.log(`  成功: ${successCount}件`);
  console.log(`  エラー: ${errorCount}件`);
  console.log('='.repeat(60));

  // 最終状態を確認
  const { count: total } = await supabase.from('subsidies').select('*', { count: 'exact', head: true });
  const { count: active } = await supabase.from('subsidies').select('*', { count: 'exact', head: true }).eq('is_active', true);
  const { count: noDesc } = await supabase.from('subsidies').select('*', { count: 'exact', head: true }).is('description', null);
  const { count: noAmount } = await supabase.from('subsidies').select('*', { count: 'exact', head: true }).is('max_amount', null);

  console.log('\n=== データベース最終状態 ===');
  console.log(`総件数: ${total}`);
  console.log(`募集中: ${active}件`);
  console.log(`概要あり: ${total! - noDesc!}件 (${Math.round((total! - noDesc!) / total! * 100)}%)`);
  console.log(`金額あり: ${total! - noAmount!}件 (${Math.round((total! - noAmount!) / total! * 100)}%)`);
}

main();
